### ISSUE TITLE
Array.from(MapIterator) problem

### ISSUE THREAD

**Issue by xsilen** [mathiasbynens/Array.from#17] opened 2015-07-16 07:42 UTC
can you make this code work well, array.from works well in my new version chrome, but lower version browser can't support array.from, the shim should support it
```javascript
var m = new Map();

m.set('strKey1',"strValue1");
m.set('strKey2',"strValue2");
m.set(function(){},"funcValue1");
m.set(function(){console.log("funcKey2")}, function(){console.log("funcValue2")});

console.log("The result is: ", Array.from(m.keys()));
console.log("The result is: ", Array.from(m.values())); 
```

**Comment by xsilen** [comment] 2015-07-16 07:43
I have commented in https://github.com/mathiasbynens/Array.from/issues/4

**Comment by ljharb** [comment] 2015-11-07 00:22
Duplicate of #4.

**Closed by ljharb** 2015-11-07 00:22 UTC
