### ISSUE TITLE
Astral symbols breaking. Is that expected? [question]

### ISSUE THREAD

**Issue by revelt** [mathiasbynens/Array.from#29] opened 2016-08-11 13:01 UTC
I'm working on a new library and I need a way to split a string by character into an array, considering Astral symbols. I was expecting this library to work, as it claims to be equivalent to ES6. But, it's not:

![screen shot 2016-08-11 at 13 53 07](https://cloud.githubusercontent.com/assets/8344688/17589218/4baaf948-5fcb-11e6-97eb-211bd9c6a171.png)
https://tonicdev.com/57ac7398a55ecf1200fa1a05/57ac7398a55ecf1200fa1a06

Real `Array.from` recognises Astral symbols fine while this library does not. Am I missing something here?

**Comment by mathiasbynens** [comment] 2016-08-11 13:20
Duplicate of #4.

**Closed by mathiasbynens** 2016-08-11 13:20 UTC

**Comment by revelt** [comment] 2016-08-11 13:26
Aha! Thanks and sorry for nuisance 😄 
I found `array-from` on npm does support Astral symbols although it's ES5< so not exact competition
